# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.26444795 0.6868216  0.97482173 0.14970822 0.69223884]
 [0.16023564 0.34884671 0.64581298 0.56201397 0.75494725]
 [0.72735263 0.55435416 0.09251479 0.9290206  0.64481947]
 [0.60204285 0.94020065 0.82126358 0.22248507 0.06889726]
 [0.38965403 0.30184597 0.78124192 0.59966469 0.11418677]]

[[-0.17364138 -0.11827747 -0.25826098  1.71268791  1.51928472]
 [-2.68142249  1.89616675 -0.07839     0.46683223 -1.06437367]
 [-1.07051572  1.36859431  0.41699407 -0.95806949 -1.07192318]
 [-0.11430526 -0.9441899   1.79744105  0.90792589 -1.14324209]
 [ 0.19741425  1.25913387  0.41646517 -3.19269628  0.52075002]
 [ 0.29895703 -0.22432396 -0.16213836 -0.9062974  -0.54682111]
 [ 0.9359519   1.43785123 -1.1800006   0.26371522 -0.44782672]
 [-0.06175061 -0.65728136  0.04175783  1.19133012 -0.86755307]
 [ 0.72329624  0.93495623 -0.16233756 -1.00966776 -0.8491883 ]
 [ 0.46177537  0.74824855 -1.1727614   1.35300013  0.20333378]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5211775728805987
1.0674273670517986


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.06889725524185852
1.8961667483253417


In [14]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-0.76762256  1.98414842  0.03073746 -1.1008575  -1.08084312 -0.1873871
 -0.40121058 -1.02997913 -0.21413962 -0.28860773 -1.08960686 -0.31741235
  0.7972079  -2.83538337 -0.30232566  0.71685663 -0.79302148  0.3455064
 -0.25879522]
-0.40121057771083546


In [15]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-1.08084312 -0.1873871  -0.40121058 -1.02997913 -0.21413962]


In [16]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-0.76762256 -1.1008575  -0.40121058 -0.28860773  0.7972079 ]


In [17]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.26444795 0.6868216  0.97482173 0.14970822 0.69223884]
 [0.16023564 0.34884671 0.64581298 0.56201397 0.75494725]
 [0.72735263 0.55435416 0.09251479 0.9290206  0.64481947]
 [0.60204285 0.94020065 0.82126358 0.22248507 0.06889726]
 [0.38965403 0.30184597 0.78124192 0.59966469 0.11418677]]
0.6458129812282398
0.6458129812282398


In [18]:
print(rand_mat[0:2,1:3])

[[0.6868216  0.97482173]
 [0.34884671 0.64581298]]


In [19]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.76762256  1.98414842  0.03073746 -1.1008575  -1.08084312 -0.1873871
 -0.40121058 -1.02997913 -0.21413962 -0.28860773 -1.08960686 -0.31741235
  0.7972079  -2.83538337 -0.30232566  0.71685663 -0.79302148  0.3455064
 -0.25879522]

[-0.76762256  1.98414842  0.03073746  4.          4.         -0.1873871
 -0.40121058 -1.02997913 -0.21413962 -0.28860773 -1.08960686 -0.31741235
  0.7972079  -2.83538337 -0.30232566  0.71685663 -0.79302148  0.3455064
 -0.25879522]

[-0.76762256  1.98414842  0.03073746  1.          2.         -0.1873871
 -0.40121058 -1.02997913 -0.21413962 -0.28860773 -1.08960686 -0.31741235
  0.7972079  -2.83538337 -0.30232566  0.71685663 -0.79302148  0.3455064
 -0.25879522]


In [20]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.26444795 0.6868216  0.97482173 0.14970822 0.69223884]
 [0.16023564 0.34884671 0.64581298 0.56201397 0.75494725]
 [0.72735263 0.55435416 0.09251479 0.9290206  0.64481947]
 [0.60204285 0.94020065 0.82126358 0.22248507 0.06889726]
 [0.38965403 0.30184597 0.78124192 0.59966469 0.11418677]]

[[0.26444795 0.6868216  0.97482173 0.14970822 0.69223884]
 [0.16023564 0.34884671 0.64581298 0.         0.        ]
 [0.72735263 0.55435416 0.09251479 0.         0.        ]
 [0.60204285 0.94020065 0.82126358 0.22248507 0.06889726]
 [0.38965403 0.30184597 0.78124192 0.59966469 0.11418677]]


In [21]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.26444795 0.6868216  0.97482173]
 [0.16023564 0.34884671 0.64581298]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [22]:
print(rand_mat)

[[3.         3.         3.         0.14970822 0.69223884]
 [3.         3.         3.         0.         0.        ]
 [0.72735263 0.55435416 0.09251479 0.         0.        ]
 [0.60204285 0.94020065 0.82126358 0.22248507 0.06889726]
 [0.38965403 0.30184597 0.78124192 0.59966469 0.11418677]]


In [23]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.14970822 0.69223884]
 [3.         3.         3.         0.         0.        ]
 [0.72735263 0.55435416 0.09251479 0.         0.        ]
 [0.60204285 0.94020065 0.82126358 0.22248507 0.06889726]
 [0.38965403 0.30184597 0.78124192 0.59966469 0.11418677]]


In [24]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.99445681 -0.79826557 -0.33151992 -1.40894891 -0.58151869  0.58499501
  0.22335285  1.39991212 -1.96305497  0.77802893 -0.0303269  -0.80652113
 -0.26139072 -0.71536139 -0.13783545]
[False False False False False  True  True  True False  True False False
 False False False]
[0.58499501 0.22335285 1.39991212 0.77802893]


In [25]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.17364138 -0.11827747 -0.25826098  1.71268791  1.51928472]
 [-2.68142249  1.89616675 -0.07839     0.46683223 -1.06437367]
 [-1.07051572  1.36859431  0.41699407 -0.95806949 -1.07192318]
 [-0.11430526 -0.9441899   1.79744105  0.90792589 -1.14324209]
 [ 0.19741425  1.25913387  0.41646517 -3.19269628  0.52075002]
 [ 0.29895703 -0.22432396 -0.16213836 -0.9062974  -0.54682111]
 [ 0.9359519   1.43785123 -1.1800006   0.26371522 -0.44782672]
 [-0.06175061 -0.65728136  0.04175783  1.19133012 -0.86755307]
 [ 0.72329624  0.93495623 -0.16233756 -1.00966776 -0.8491883 ]
 [ 0.46177537  0.74824855 -1.1727614   1.35300013  0.20333378]]
[1.71268791 1.51928472 1.89616675 0.46683223 1.36859431 0.41699407
 1.79744105 0.90792589 0.19741425 1.25913387 0.41646517 0.52075002
 0.29895703 0.9359519  1.43785123 0.26371522 0.04175783 1.19133012
 0.72329624 0.93495623 0.46177537 0.74824855 1.35300013 0.20333378]


In [26]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.99445681 -0.79826557 -0.33151992 -1.40894891 -0.58151869  0.58499501
  0.22335285  1.39991212 -1.96305497  0.77802893 -0.0303269  -0.80652113
 -0.26139072 -0.71536139 -0.13783545]

[-0.99445681 -0.79826557 -0.33151992 -1.40894891 -0.58151869 -5.
  0.22335285 -5.         -1.96305497 -5.         -0.0303269  -0.80652113
 -0.26139072 -0.71536139 -0.13783545]


In [27]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [28]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [29]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.17364138 -0.11827747 -0.25826098  1.71268791  1.51928472]
 [-2.68142249  1.89616675 -0.07839     0.46683223 -1.06437367]
 [-1.07051572  1.36859431  0.41699407 -0.95806949 -1.07192318]
 [-0.11430526 -0.9441899   1.79744105  0.90792589 -1.14324209]
 [ 0.19741425  1.25913387  0.41646517 -3.19269628  0.52075002]
 [ 0.29895703 -0.22432396 -0.16213836 -0.9062974  -0.54682111]
 [ 0.9359519   1.43785123 -1.1800006   0.26371522 -0.44782672]
 [-0.06175061 -0.65728136  0.04175783  1.19133012 -0.86755307]
 [ 0.72329624  0.93495623 -0.16233756 -1.00966776 -0.8491883 ]
 [ 0.46177537  0.74824855 -1.1727614   1.35300013  0.20333378]]



In [30]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.14970822 0.69223884]
 [3.         3.         3.         0.         0.        ]
 [0.72735263 0.55435416 0.09251479 0.         0.        ]
 [0.60204285 0.94020065 0.82126358 0.22248507 0.06889726]
 [0.38965403 0.30184597 0.78124192 0.59966469 0.11418677]]

[[-0.17364138 -0.11827747 -0.25826098  1.71268791  1.51928472]
 [-2.68142249  1.89616675 -0.07839     0.46683223 -1.06437367]
 [-1.07051572  1.36859431  0.41699407 -0.95806949 -1.07192318]
 [-0.11430526 -0.9441899   1.79744105  0.90792589 -1.14324209]
 [ 0.19741425  1.25913387  0.41646517 -3.19269628  0.52075002]
 [ 0.29895703 -0.22432396 -0.16213836 -0.9062974  -0.54682111]
 [ 0.9359519   1.43785123 -1.1800006   0.26371522 -0.44782672]
 [-0.06175061 -0.65728136  0.04175783  1.19133012 -0.86755307]
 [ 0.72329624  0.93495623 -0.16233756 -1.00966776 -0.8491883 ]
 [ 0.46177537  0.74824855 -1.1727614   1.35300013  0.20333378]]
[[3.         3.         3.         0.14970822 0.69223884]
 [3.         3.    

In [31]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.14970822 0.69223884]
 [3.         3.         3.         0.         0.        ]
 [0.72735263 0.55435416 0.09251479 0.         0.        ]
 [0.60204285 0.94020065 0.82126358 0.22248507 0.06889726]
 [0.38965403 0.30184597 0.78124192 0.59966469 0.11418677]]

[[3.         3.         3.         0.14970822 0.69223884]
 [3.         3.         3.         0.         0.        ]
 [0.72735263 0.55435416 0.09251479 0.         0.        ]
 [0.60204285 0.94020065 0.82126358 0.22248507 0.06889726]
 [0.38965403 0.30184597 0.78124192 0.59966469 0.11418677]]
